name: Azure Functions CICD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'backend/**'  # backendフォルダ以下の変更のみを監視

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Setup Java'
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: 'Build Project'
      run: |
        cd backend
        chmod +x ./gradlew
        ./gradlew build
      
    - name: 'Upload artifact for deployment job'
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: './backend/build/libs/*.jar'
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Functions'
      uses: azure/functions-action@v1
      id: fa
      with:
        app-name: 'BBoard'
        package: './backend/build/libs/'
        publish-profile: ${{ secrets.AZURE_FUNCTIONS_PUBLISH_PROFILE }}

    - name: 'Logout of Azure CLI'
      run: az logout
